### ISSUE TITLE
Logo #6

### ISSUE THREAD

**Issue by maartentibau** [manekinekko/xlayers-logo#6]
## Logo preview (in PNG or SVG)
<img src="https://www.webtrix.be/xlayers/xlayers-wip1.png" />

## Your full name
Maarten Tibau

## Your Twitter (or Github) handle
@maartentibau

**Comment by maartentibau** [comment]
The shape of the X could be different, colors as well.. but I guess you get the idea :smiley:

**Comment by maartentibau** [comment]
## LGBT version
<img src="https://www.webtrix.be/xlayers/xlayers-lgbt.png" />

**Comment by manekinekko** [comment]
The winner is logo #11.
